---
title: "Create Tree Model"
author: "C"
date: "November 15, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Load Libraries
```{r}
library(ggplot2)
library(party)
library(rpart)
```

Load Data frame 

```{r}
df1 <- read.csv("AAA_Data_for_Tree.csv")

```

Remove X Variable

```{r}

df1 <- df1[,-1]
```

Split the data into a training set and test set (75% of data to training and 25 % of training to Test).

```{r}
n = nrow(df1)
train = sample(1:n, size = round(0.75*n), replace=FALSE)
df1.train = df1[train,]
df1.test = df1[-train,]
```


Build the decision tree

```{r}

tree <- ctree(factor(final_result) ~ homepage + forumng + glossary + dataplus + oucollaborate + oucontent + resource + subpage + url, data=df1.train)

```

Plot the tree

```{r}

plot(tree)

```

Test the deciscion tree

```{r}
df1.test$prediction <- predict(tree, df1.test)

```

```{r}
c2.tree <- rpart(prediction ~ homepage + forumng + glossary + dataplus + oucollaborate + oucontent + resource + subpage + url, data=df1.test) 
printcp(c2.tree)
rpart(formula = prediction ~ homepage + forumng + glossary + dataplus + oucollaborate + oucontent + resource + subpage + url, data = df1.test, method = "class")
```

Check performance of the model using a confusion matrix

```{r}
table(df1.test$final_result, df1.test$prediction)

```

Visulaize results 

```{r}
tree_confusion <- as.data.frame(table(df1.test$final_result, df1.test$prediction))

tree_plot <- ggplot(tree_confusion)

tree_plot + geom_tile(aes(x=Var1, y=Var2, fill=Freq), color = "gray") + scale_x_discrete(name="Actual Class") + scale_y_discrete(name="Predicted Class") + scale_fill_gradient(high = "red") + labs(fill="Frequency", title = "Decision Tree Confusion Matrix") + geom_text(data = tree_confusion, aes(x=Var1, y=Var2, label=Freq), color = "white")

```
